Repository oacore/about, pull requests merged in 2020-08, with the labels that each got.

#234 Add missing title
  components/page/page.jsx
  data/accessibility.md
Labels: bug

#237 Remove missing screenshot
  data/services/connector.yml
Labels: bug

#232 Fix section
  components/content/article.jsx
  components/content/content.scss
  components/content/section.jsx
  components/error.jsx
  components/pages/markdown.jsx
  components/pages/service.jsx
  data/accessibility.md
  pages/index.module.scss
  pages/services/index.jsx
Labels: feature

#242 Fix data/providers page look
  pages/data/providers.jsx
Labels: bug

#244 Remove Bootstrap Container from Section
  components/content/article.jsx
  components/content/content.scss
  components/content/section.jsx
  components/hero/hero.scss
  components/pages/service.scss
  components/sections/join.jsx
  components/sections/join.scss
  pages/about/about.module.scss
  pages/about/index.jsx
  pages/data/providers.jsx
  pages/index.jsx
  pages/index.module.scss
Labels: feature, help wanted
